### PR TITLE
with Resizable, now the whiteboard page looks like Leetcode(a resizable divider that allows dynamic distribution)

### PR DESCRIPTION
**Pull request by Edwardd02**
This is my plan on updating UIs of our whiteboard

1. The content in the help button will go HelpModal, HelpModal will contains a instruction of using whiteboard.
2. the Help button will become the hint button.
3. All the buttons will at a better loaction.
4. Bug to fix: the resizable divider problem, when you move to minimize the quetsion part, it should only have two state, disappear or larger or equal to its min size, now you can move it to a very small size which is wierd.

### CODE REVIEW

**Review by VinceLukban — CHANGES_REQUESTED** [review]
do better Edward. Haha, just kidding. I'm requesting changes to the scrolling to be either floating or vertical or a tooltip

**Comment by Edwardd02** [comment]
Your request will be processed in my pull request, please merge this one for now because I have major changes on UIs as well as other changes

**Comment by DeanRoos** [comment]
Looks good, maybe we can revisit how the question is prompted later

**Review by VinceLukban — APPROVED** [review]
looks great

**Pull request merged**
